site_name: "Vorkurs Programmierung"

nav:
  - Übersicht: index.md
  - "Kapitel 1 – Einführung in Python": content/kapitel1.md
  - "Kapitel 2 – Python-Setup & Arbeitsumgebung": content/kapitel2.md
  - "Kapitel 3 – Strings & Text verarbeiten": content/kapitel3.md
  - "Kapitel 4 – Datentypen, Variablen & Ein-/Ausgabe": content/kapitel4.md
  - "Kapitel 5 – Kontrollstrukturen": content/kapitel5.md
  - "Kapitel 6 – Schleifen & Listen": content/kapitel6.md
  - "Kapitel 7 – Funktionen & Module": content/kapitel7.md
  - "Kapitel 8 – Dateien, CSV & JSON": content/kapitel8.md
  - "Kapitel 9 – Mini-Automationen": content/kapitel9.md
  - "Kapitel 10 – Dictionaries & Datenstrukturen": content/kapitel10.md

theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: orange
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: DM Sans
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.prune
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/theme.css
  - stylesheets/grid.css
  - stylesheets/logo.css
  - stylesheets/video_admonition.css
  - stylesheets/mermaid.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - macros

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://de.linkedin.com/company/qualidy
    - icon: fontawesome/solid/globe
      link: https://qualidy.de

watch:
  - tasks

copyright: Copyright &copy; 2026 Qualidy GmbH
